; (add-to-list 'load-path "/usr/local/share/maxima/5.18.1/emacs/")
; (add-to-list 'load-path "/home/SSCO_HQ/cspannri/.elisp/imaxima-imath-1.0/")
(autoload 'maxima-mode "maxima" "Maxima mode" t)
(autoload 'imaxima "imaxima" "Frontend for maxima with Image support" t)
(autoload 'maxima "maxima" "Maxima interaction" t)
(autoload 'imath-mode "imath" "Imath mode for math formula input" t)
(setq imaxima-use-maxima-mode-flag t)